objects/Loyalty_Reward_Point__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loyalty Reward Points (Account)</relationshipLabel>
        <relationshipName>Loyalty_Reward_Points1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Point__c</fullName>
        <label>Point</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Earned</fullName>
                </value>
                <value>
                    <fullName>Spent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loyalty Reward Point</label>
    <language>en_US</language>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Loyalty Reward Point Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Reward Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LoyaltyPoints.cls
public with sharing class LoyaltyPoints {
    
    @AuraEnabled(cacheable=true)
    public static List<Loyalty_Reward_Point__c> getConsumtion(String accountId) {
        List<Loyalty_Reward_Point__c> consumtion = new List<Loyalty_Reward_Point__c>();

        try {

            if(Schema.sObjectType.Loyalty_Reward_Point__c.fields.Account__c.isAccessible()
                && Schema.sObjectType.Loyalty_Reward_Point__c.fields.Point__c.isAccessible()
                && Schema.sObjectType.Loyalty_Reward_Point__c.fields.Type__c.isAccessible()
                && Schema.sObjectType.Loyalty_Reward_Point__c.fields.CreatedDate.isAccessible()
                ) {

                consumtion = [
                    SELECT Account__c, Point__c, Type__c, CreatedDate
                    FROM Loyalty_Reward_Point__c
                    WHERE Account__c = :accountId
                    ORDER BY CreatedDate DESC
                ];

            }
        } 
        catch(Exception ex) {  
            System.debug('exception: ' + ex.getMessage());
            throw ex;  
        }
        return consumtion;

    }

    @AuraEnabled(cacheable=true)
    public static Decimal getLoyaltyPointsTotal(String accountId){
        
        Decimal total = getAccountLoyaltyPoints(accountId);

        return total;

    }

    public static Decimal getAccountLoyaltyPoints(String accountId) {

        Decimal total = 0;

        if(Schema.sObjectType.Loyalty_Reward_Point__c.fields.Account__c.isAccessible()
                && Schema.sObjectType.Loyalty_Reward_Point__c.fields.Point__c.isAccessible()
                ) {
            AggregateResult[] AggregateResultList = [SELECT Sum(Point__c)points FROM Loyalty_Reward_Point__c where Account__c = :accountId and Point__c != null];

            if(AggregateResultList != null && AggregateResultList.size() > 0){ 

                Object sumPoints = AggregateResultList[0].get('points');

                if(sumPoints != null) {
                    total = (Decimal)sumPoints;
                }

            }

        }

        return total;

    }
}